module Drama
  module Constants
    PEOPLE = [
      'G.M.',
      'Alex',
      'Divad',
      'Dominic',
      'Saviiator',
      'Samy',
      'Amp',
      'Timmy',
      'the god of gaming',
      'DMG',
      'PStar_Luigi',
      'shay',
      'Master Roxas',
      'envy',
      'JD Dark',
      'LightElementa',
      'Chandelure',
      'E-77',
      'King Atlas',
      'Archknight',
      'Hekya',
      'scorpion',
      'bluewilliam7',
      'Sly',
      'Paul',
      'systeminspired',
      'Ultra',
      'MadTyro',
      'king_chris',
      'Pikachu24Fan',
      'ItsJordanB',
      'muffinman',
      'Bean Boy',
      'AyAyRon',
      'Dag3DR',
      'Gibstack',
      'Spwook',
      'The Great Cat Fish',
      'Jupi',
      'Davistres',
      'ImNotGamer',
      'O w e n',
      'Sxips',
      'frono',
      'MarioBrawler',
      'Fakkiro',
      'Big Lad penguin',
      'Solar',
      'Raiden',
      'SuperCenation98',
      'Finch',
      'Rumtin',
      'Shyguy48',
      'Super Tails',
      'MrRavine',
      'The_Izlander',
      'Mr. ToadTheGamer',
      'BBBC_NEWS',
      'OutrageousDWB',
      'P-Merks',
      'Catzador',
      'WaffleCaptain',
      'AgentTortoise',
      'G I A N',
      'Airsola',
      'Munchkin',
      'LocaMash',
      'Balpv',
      'Edx',
      'Xenxli',
      'ZackAttack',
      'Noah',
      'Wave',
      'Osha',
      'Gryphon',
      'Typh',
      'Replaisment',
      'Nick9572',
      'Queen Nio',
      'Falconpunch',
      'ZippyVirus',
      'blackjesusjrf',
      'LHB',
      'Kohai',
      'Mark G.',
      'Braediac',
      'Mary The Jeffries',
      'idfiander',
      'Fozzy',
      'Crying Sobble',
      'KilledTheJoke',
      'WeridenXP',
      'Marly',
      'ElegantMatt',
      'Lomiuju',
      'Gadget Boy',
      'Fat Man',
      'hiromasaold',
      'Jakob and Rosalina',
      'Raccoon Thunder Mario',
      'Arq',
      'D-Stacks',
      'Dakimeon',
      'L4z3rbrzn',
      'Flamespitter',
      'Kenneth',
      'froggydojo',
      'Epoodle',
      'DJ Daft Duck',
      'LordKreig',
      'Tarrmantis',
      'Swiftdeath76',
      'W1n',
      'Antman03',
      'Bluedelirium',
      '__Audacity',
      'Bomber',
      'ZeroGx4',
      'SpaceMadness',
      'Kevin',
      'DaffyDethklok',
      'galaxy',
      'LC',
      'Deefect',
      'Boshi',
      'Pepper',
      'Nivlakk',
      'Frog Mario',
      'Hydra',
      'Mighty',
      'Rei Ayanami',
      'funnynumbers',
      'Ripoob',
      'Ambi',
      'DevvyStar',
      'SuperPopple',
      'Celery',
      'Darkwolf',
      'DioBrando',
      'Parashoe',
      'TiringCoyote',
      'Epsilon Lord',
      'Cel',
      'Brady',
      'Deniair',
      'Rack',
      'Reed',
      'RouterBomb',
      'lil oatty',
      '9thBit',
      'Nikky',
      'Afrojr',
      'AetherArchivist',
      'ShizNugget',
      'VenYZY',
      'SoniSwitch',
      'Stebop',
      'dtoxicTrogor',
      'Little_Mac',
      'Ninja JaYmAn',
      'HAK777',
      'Shop Keep',
      'SCAlex',
      'Anz',
      'ojo',
      'Holio15512',
      'High Octane Corn Syrup',
      'Jerry',
      'Tamloo',
      'Sousuke Kirigiri',
      'Jeffery',
      'ThunderTech',
      'aron593',
      'EphemeralEmerald',
      'FoX',
      'Kazmandude',
      'Clownpilled',
      'FrozenAlive97',
      'The Living Drawing',
      'Django',
      'Sn4p3rn00b',
      'Asgoel',
      '5H4N3',
      'DaDerpyKid',
      'Ruby',
      'gamemasterlink',
      'MygL',
      'ImAcebtw',
      'Huedenne',
      'Ophion',
      'Flim',
      'SavageJacek20',
      'Garioshi',
      'Mrmariobros222',
      'MPS64',
      'Matt',
      'nima74',
      'DilawZ08',
      'Nekonomicon',
      'Trystanater',
      'Peanut',
      'dalerben61',
      'Barricade',
      'Drelladin',
      'kirb',
      'Zero',
      'Annie',
      'ArchfiendXRose',
      'Kelmo',
      'GamerRye',
      'PLRageman',
      'Brea_F',
      'HazelAzazel',
      'Kayla',
      'Sans the Comic',
      'Mowgy',
      'JustinM',
      'Slugs',
      'chimchar101',
      'Pat',
      'StrongCrocodile',
      'Determinedboss',
      'Nack',
      'SouljaSleet',
      'NESFilipGamer',
      'Supaluigi62',
      'YRay',
      'Bear',
      'Green de la Bean',
      's7_',
      'SpongYoshi',
      'Gwen',
      'Creptiqal',
      'Frog',
      'that1yoshi',
      'Didderd',
      'Szion',
      'Craymotherlol',
      'Jordan',
      'SkilledRoy',
      'Reaperr',
      'Charlie_A',
      'CrushforceX',
      'Cousin Nicky',
      'Mapper',
      'M4yro',
      'AwshomeHat',
      'WolfgangLombard',
      'Race',
      'LegendarySerperior',
      'SilverJ',
      'Kenko Shinkuma',
      'Kibble',
      'Naccirdaisy',
      'Nebby',
      'Loks63jr',
      'EvanEMV',
      'REXROY82',
      'muscleman',
      'Smack Jack',
      'Alvin4500',
      'Mayor Noggenfogger',
      'Teraok',
      'TLonelyG',
      'Ring',
      'Tray',
      'Pepper Ph.D',
      'SUPPA POTATO',
      'Frankie',
      'Mjeyy',
      'Redgee',
      'william1',
      'PyroBlossomTech',
      'Calvin Harris',
      'ForgottenRecusant',
      'Jahven',
      'ZoloraVH',
      'DeeGreen',
      'Major Nick',
      'KDestroyer9',
      'Fulton Boss',
      'Fira King',
      'bionic_yoshi',
      'Gordo98',
      'drifti',
      'doodz',
      'Charr94',
      'TyTy',
      'KooCie.Jar',
      'SayoDreem',
      'KMidnite',
      'GmanSir',
      'Honor',
      'thatdude6758',
      'Lain',
      'Neri',
      'ZayZenBlaze',
      'Snipman',
      'Elfman',
      'Veenoo',
      'Knuckles5577',
      'Devin',
      'Rohan',
      'Azzy',
      'BagelBoy',
      'Lightshock16',
      'marsroverll',
      'dolphinliam',
      'Lukey',
      'Fon',
      'YearlyParty',
      'Zanudus',
      'Sunset Stanza',
      'Meary',
      'Zybax',
      'KaaK',
      'SilverSamurai905',
      'sliced oxy',
      'Dragaux',
      'The Fabian Strategy',
      'Lunch Box',
      'battledude777',
      'Lilbabyslut',
      'txshark1999',
      'BOSS_HABIBI',
      'Furymon',
      'Enar',
      '0.22619048',
      'MasterCrack',
      'Joakim',
      'Jarechidna',
      'smallfry',
      'BustMyMilk',
      'Chrispy',
      'bayobands',
      'LucasThe67thQQQ',
      'Super Paulio',
      'linguine',
      '7thRenegade',
      'Dork',
      'Doomddtb',
      'Dave',
      'GreenBean',
      'DemonBreaker',
      'Malurth',
      'DoctorMario',
      'laluc',
      'Nitro',
      'Pizano',
      'Ethan',
      'Alexis0900',
      'Panchito',
      'AceEliteMaster',
      'DreamyLuigi',
      'RetroSinge',
      'LogaSoba',
      'Ivan_Barr',
      'TheGamer91',
      'Ultimate Legend',
      'el giraffe',
      'Ribbot',
      'DaBluePittoo',
      'AJHuygaRose',
      'Cloudpaw',
      'Mega',
      'xero',
      'Kazoo',
      'Lino',
      'smeth',
      'Wolfdanthegamer29',
      'Char',
      'Gordo',
      'BradHeat',
      'DrearierHalo',
      'ThyMofoPrincess',
      'ValiTheCali',
      'ElClles',
      'saintd_ii',
      'TrashTeen',
      'Daxter',
      'Timmiev99',
      'biziometa',
      'Supernova888',
      'TimeSmash',
      'MarioSpore',
      'EmjayGamer19',
      'evilforever_666',
      'Selfmade\_/Darkness',
      'Mister_Clems',
      'artsy',
      'TheBassSinger',
      'Rufix.LP',
      'JMeister64K',
      'Lord Scorgizm',
      'Papple',
      'The Walrus King',
      'jonah',
      'Memester',
      'Tana',
      'cyberpunk',
      'Varkai',
      'AvBW',
      'RexMontanaKingston2014',
      'Dayvon',
      'Trojan64',
      'pvdilla.exe',
      'Joseph',
      'Nazzax',
      'TheSuperEan300',
      'Adderti',
      'Saviñon',
      'bolds',
      'Chris250505',
      'Vegito1019',
      'Pootendo',
      'Kimimaru',
      'Focus_Fiasco',
      'Landon',
      'Hypersonic',
      'Cryxill',
      'Slipity Slam',
      'Blur',
      'Toxxik',
      'Debo',
      'Cure',
      'Rakyy',
      'Super smash',
      'Neojin',
      'RPG',
      'Ne0',
      'Willdabomb',
      'sotz33',
      'VileVel',
      'Nora',
      'Kellen',
      'GutsyStrawberry',
      'NextDoorNeighbors',
      'w0tt',
      'Gingerham',
      'Zack230',
      'Mack R-S',
      'Harry',
      'Chloroform',
      'KillerAwesome',
      'heroflow',
      'LML123',
      'guttaslymm',
      'coolmario3443(Nelson)',
      'JinjoGuy',
      'Thomas/BJG',
      'Ev',
      'X-Pac',
      'Snmario',
      'BeamBag',
      'Thumbs',
      'ElliotThu',
      'weird',
      'Mr.CornMan',
      'SaffronGrape',
      'David Pickett',
      'Bup',
      'Frisky',
      'Maath',
      'Bleb',
      'ElectricRainbow7',
      'Val',
      'HugMyButt',
      '$tarman25',
      'DePereppedood',
      '2Steve',
      'Bjinmarolo',
      'Easiestcc',
      'Mr SkyLot',
      'Kole',
      'denvis',
      'Craig',
      'DarkSpine',
      'Starguy',
      'Tyler99',
      'justgaming',
      'Ellebazi',
      'Redjuls',
      'Sherwood',
      'ThymeMaster',
      'Superjo',
      'KARBONNESTEEL',
      'Rabid',
      'Pacodios',
      'Shad',
      'MrGuy',
      'andy',
      'Notonyourlevel',
      'Togik Suki',
      'Garrett',
      'NoEffsGiven',
      'Sandy Claws',
      'Ulysilve',
      'ReiDriana',
      'Pear',
      'Snakefire7',
      'Matter NOVA',
      'Cokeland Saxton',
      'Bardz',
      'Pathetic',
      'NoahTom',
      'Michael41Billion',
      'SOUSAMASTA47',
      'Spagkitty',
      'Aguni',
      'SamMcKdamn',
      'rampage',
      'RalphHibikiKnight',
      'Erich',
      'Flurp',
      'Slem',
      'ZBH51423',
      'Zed',
      'Konic.wav',
      'M14',
      'swiftavocados',
      'UnluckyLucky',
      'WhyBother',
      'Fargus46',
      'dooofi',
      'Zega1234',
      'Tyruzi',
      'InvaderLum.PNG',
      'dylanthedudegames',
      'smiggy',
      'Lego Mario',
      'Bojangles4th',
      'FromGAMER',
      'egg',
      'Incompetant Bagel',
      'Luigiman3YT',
      'Dawn&Dusk',
      'Wylder',
      'TheGamerDuo',
      'supergalaxy',
      'Haren',
      'DannyDuckie',
      'RichardBanibensu',
      'GameX',
      'EwanSometimes',
      'Celine',
      'dennis_silvero',
      'kenzie',
      'Arceus Killer',
      'Ballin_GamerZ',
      'Riley524',
      'Nuceria',
      'LazyBones',
      'moarkraps',
      'Kenny961',
      'mikemotobike',
      'gemsticks',
      'Crille',
      'Reib',
      'theanh',
      'gr33n',
      'TubularBells',
      'Acarpie',
      'confused',
      'Cerberus9',
      'Rpg_Nasty',
      'Silv3rstephano',
      'Platypus',
      'Sigma9821',
      'wolfpac',
      'Blue Tea',
      'sec',
      'snowtauren',
      'Zyphyx',
      'Chronicle2',
      'Kaosu',
      'vexoskeleton',
      'Mexican Spongebob',
      'Hypnotron',
      'Pomathan',
      'Dr.Piss',
      'Blame_Others',
      'amiZa',
      'RocketStar',
      'SeanyDali',
      'Alex D. Luffy',
      'Lewdgril',
      'DragonFlame42',
      'words',
      'Toasted',
      'Rcx',
      'AkumaSanzu',
      'That Ain\'t Falco',
      'Ender',
      'MauAkino',
      'Victor',
      'blob_15',
      'Razer',
      'Tet',
      'Jcm906',
      'SanityZetpe',
      'goobert',
      'KlicKlac',
      'OnGod',
      'GEE GOLLY',
      'Barkley',
      'Kyu',
      'Dr Nintentrev',
      'Maurice',
      'Nerv',
      'Black Yoshi',
      'SSK',
      'Casey',
      'ACrush14',
      'UBSS5',
      'Angel',
      'Ai',
      'Darth Baum',
      'POCARI SWEAT',
      'LLZ | Lov3',
      'ALEXANDER ME',
      'megamario359',
      'Isopod',
      'Jurj Clooners',
      'Tortugas',
      'Trxn',
      'marioluigijam',
      'broke bicht',
      'Mushroom Man',
      'DJTheRoman',
      'KrayzieBone214',
      'SS Oreo',
      'Nacho Chan',
      'Dr. Fajita',
      'LittleToonCat',
      'Twilight01',
      'Sod-Y',
      'Jaden',
      'Urlogic',
      'agents8s',
      'dayer69',
      'Sen',
      'Colin',
      'L!LMexican',
      'M0niak',
      'ignacio',
      'SpaceVin',
      'Jefferino',
      'Crakajaaka',
      'Boxhead',
      'MeltingIceCaps',
      'Falklore',
      'Minty',
      'EnjoiHunt',
      'Ellis',
      'OldGreg97',
      'MakoMateria',
      't0zen',
      'Loved',
      'wooper',
      'Friendfreak',
      'SandVich',
      'shy guy',
      'Hydrochlorination',
      'Chairman Mao Zedong',
      'Clem',
      'Aqur',
      'Mother/EB',
      'Clandestiny',
      'Superbit',
      'Soup',
      'tyler',
      'Sirk',
      'Fuzzyness',
      'Snowglobes',
      'MasterRawWeed',
      'Ryan',
      'Bid',
      'RoboticTea',
      'Deathaura',
      'dood',
      'Dimenton',
      'woponese',
      'Pokemongenius',
      'soma',
      'burgerpizzamike',
      'yung zaku',
      'BloodMuffin',
      'Grasp',
      'PinkGoldPichu',
      'PixelP',
      'Dwag',
      'YoloPowah03',
      'ChaoGardner',
      'Comitted',
      'Sennyu',
      'Wing',
      'ArkOfJustice',
      'Doma995',
      'drewes35',
      'Dass',
      'MarkyGDawg',
      'Godot',
      'Zubats',
      'Los1ng',
      'Pannash',
      'Rabbidfan0511',
      'Nybbles',
      'seanathan',
      'b e g r i p',
      'DawnOfSolace',
      'Paradox',
      'Maiku',
      'The FooL',
      'Dawsauce',
      'Kevbot',
      'Lone Latios',
      'Raiquis',
      'kingXwillem',
      'Ringo',
      'Felix',
      'ZEF',
      'LeifSDS',
      'Kyrsaku',
      'Murmurer',
      'Jordanfred',
      'namuh',
      'Shaumbra',
      'b_b',
      'ice climber',
      'Chango Hango',
      'ItzMartyyy',
      'jj11367',
      'TheGreatLazyBum',
      'Doofi',
      'Ren',
      'MoltenPops',
      'Johnf',
      'SkeletonDude',
      'Dexterspet',
      'sefszdawwedqw',
      'ChrissyTheSquirrel',
      'spCrossing',
      'SuburbanWitcher',
      'SuburbanWitcher',
      'BIGMIKE03',
      'pedrocrvg',
      'Smidsy',
      'LeafBladeSupreme',
      'Greenmage',
      'Wardle',
      'fabioandthecastles',
      'No Name Animator',
      'Aero',
      'BrainKK',
      'Abe',
      'Alserex',
      'Peptobislawl',
      'TrappedSpring',
      'mike',
      'Crimson',
      'Squizzard',
      'Igotwrecktd',
      'Lisreal',
      'Ken',
      'Akumati',
      'Altair',
      'HonorableLag',
      'Tetrias',
      'OnePokeMan',
      'Albinum',
      'Anderre Belmont',
      'Gus',
      'Dr.Nic',
      'UltiMike',
      'XPhantom',
      'Gatto',
      'Francis',
      'Amir',
      'Molovo',
      'Terra',
      'knoms',
      'knoms',
      'Bluz',
      'Majin',
      '-md',
      'QB',
      'Doopliss',
      'Lupy',
      'Niko92',
      'bobbyboi',
      '0ffBe4t',
      'Ghosty',
      '!Hiddemeister',
      '!Hiddemeister',
      '!Hiddemeister',
      'Dembo',
      'freshflower',
      'Luks_18',
      'Toad Stool',
      'Waffler',
      'Sdia',
      'Butters',
      'Sinoj',
      'Akiyo Scarlet',
      'hero',
      'Frisk',
      'Xear',
      'Breath of Teriot',
      'HarDe',
      'Hutty',
      'LarryLeichester',
      'LaughinZombie',
      'Lulurun',
      'Nugget',
      'DeluxeCN',
      'Slaking',
      'Memelord420',
      'Muse24',
      'shyguyking',
      'Mighty Morphin',
      'Sleepy-Tenda',
      'Virgash',
      'gamemasterplc',
      'fare67t',
      'Jessykhov',
      'pushmipullu',
      'Dark Met a Knight',
      'Fancy',
      'Minus',
      'Batanna',
      'Shadic0',
      'zvbgamer',
      'Max days-e',
      'Saul Goodman',
      'Bill Cosby',
      'Jacob',
      'Vinceomega1',
      'Krix08',
      'Tinymo',
      'Corum',
      'Mister',
      'Brother Rock',
      'Cat',
      'Makin',
      'Qwarke',
      'Waluigi(tm)',
      'xx420xx',
      'mxrti zcc',
      'blekyboi',
      'Celery +',
      'Crossover',
      'DrunkPenguinz',
      'Frazman',
      'Fury20',
      'GreenKnight',
      'Hayden',
      'Heb',
      'Jakeburris10',
      'KalebR6',
      'kni6htfriend',
      'Lucar',
      'MikeTheMintMan',
      'Peridough',
      'ScrubSpeedrunner',
      'Lyzder',
      'Yossi Amran',
      'FireEmblemPeach',
      'Michal',
      'Chezz',
      'Cruxis',
      'DannyEpidemik',
      'GallyG',
      'JMFNG',
      'Kokonoe',
      'Kyobi',
      'Mando',
      'Marioy0',
      'Mcloving',
      'OmRid64',
      'Rain',
      'Raspherbel',
      'Rcs',
      'Ryadh',
      'slagathor',
      'YoshiCoolFan',
      'Shadow Monk',
      'Sketch',
      'Sparky',
      'Virus',
      'corruptedpixels',
      'corruptedpixels',
      'SuperStarnuggets',
      '3 Dolphins',
      'adaptsj',
      'Airweiner',
      'Ajdin',
      'Alfredo',
      'Anthony',
      'Bearclaw',
      'Blade',
      'BroadwayCJ97',
      'ChrisNonymous',
      'CollegeBoy',
      'CreativeUsername',
      'Flootin',
      'Fooruman',
      'Geo',
      'Groose',
      'Hellfoes',
      'judojamie',
      'mrassumedname',
      'MrCarlesX',
      'Oce33',
      'Pope Frederick',
      'Princess J',
      'PwNeDoScAr',
      'Ragemaster',
      'sickboy',
      'Stanka',
      'tmr',
      'Toasty',
      'Wolfang28',
      'Alexander Supertramp',
      'aquamaster9',
      'Baconburglar',
      'Smance',
      'That guy with the spoon',
      'warkatz',
      'EliGamerX',
      'DesCaFeinado',
      'Fixed Fun',
      'Verbal Kint',
      'mikeshell86',
      'YEFE',
      'MoonlitxShadows',
      'Avril (nyan)',
      'Mizuhara',
      'Expels',
      'Knight',
      'Ghi',
      'The Tilted God',
      'Pink Switch',
      'Deathum',
      'PrimoMattattack',
      'Neo',
      'Letho',
      'Froge',
      'xD',
      'Naomi Shimizu',
      'Optllizer',
      'Cavana',
      'robothing',
      'mickluvin619',
      'KingK',
      'QR99ST',
      'Ike',
      'Gem',
      'LuckyTails',
      'ILOVEVHS',
      'Krystof',
      'Catherine',
      'blacksunshine',
      'James the DragN',
      'Papa Juan',
      'Pomini',
      'So6p juubito Uchiha',
      'Seven',
      'Captain',
      'Anna Sun',
      'Zukari',
      'Justin',
      'RedTheMage',
      'ShinigamiSteve',
      'Gnorf',
      'Fiercekyo',
      'RodoStyle',
      'Link',
      'Kenny Lloyd',
      'Cpt Andu',
      'NinjaSuperGaming',
      'CrimsonPotatoKing',
      'Mr.Triplecard',
      '9bladesofice',
      'Bellamy',
      'Princessa',
      'Altan',
      'MH Sam',
      'ShinySP',
      'Artik',
      'Chikun',
      'PierreLuk',
      'G.E.N.O.S',
      'Wackko',
      'jiazji',
      'Trippy',
      'Laggyb0i',
      'ColaXin',
      'Gen',
      'Tspeeds',
      'The_Fabricator',
      'Purple Plan',
      'Wolf',
      'Viggzplashfilms',
      'Rigby',
      'REDDARK',
      'weegro',
      'doctorbattle',
      'Cammoon',
      'Zundrel',
      'Yikezz',
      'Frogtron',
      'SpoopyBolt666',
      'GTX 1080 (Allen/Amy)',
      'Silvercario',
      'SmilingInMonotone',
      'Umehara',
      'BreakTargets',
      'Mr. Perfect',
      'BalpaBoi',
      'Malefactor',
      'Mythra Main',
      'Chewi',
      'Koletrain904',
      'Whatever31840',
      'Arix23',
      'ColonialHunter',
      'ZeroSpoons',
      'Mail May',
      'Star Breaker',
      'Jettpizza',
      'lukefc',
      'hubworld23',
      'Decade',
      'enrgy',
      'Lightlanayru',
      'Jordo',
      'ATA v AzZaZin',
      'Legit Mustang',
      'Saiyan',
      'zrb',
      'White_Pikmin',
      'TNTBlowzUp',
      'matt.',
      'HipposaurusDip',
      'jealous of nikki',
      'Wreckening',
      'Duwang',
      'Pie',
      'Fluttershy0471',
      'Sager',
      'Fardulf',
      'squiddy0525',
      'porcaroPOC',
      'Sub',
      'DankDoge420',
      'ManSporks',
      'Kaine',
      'SonicRyan',
      'Aoostan',
      'Party Poison',
      'Inari',
      'Shmowzow',
      'Calvin',
      'Pike',
      'Lexie',
      'Fate',
      'Jelly667',
      'Shermdoof',
      'Dark',
      'Saures',
      'RoboSpongie',
      'Astrotropics',
      'Ricky Dupon',
      'Renzokuken',
      'TheMightyPikachu',
      'general winter',
      'Chestonic',
      'Dabble',
      'lil two car garage',
      'Ryuu',
      'Sarah',
      'StuntMastah',
      'Wizop',
      'NotMyNumber',
      'Solum',
      'UppercaseOne',
      'Bananapa',
      'Trigonom',
      'Raven.',
      'iStayRushing',
      'SOLEIL',
      'RoboMWM',
      'ADDICT',
      'Krandel',
      'Akara',
      'Christian',
      'Emilee',
      'Lenny',
      'Lissom',
      'SlickBlackibensu',
      'Vilvalas',
      'Ronney',
      'LumpOMeat',
      'ofthedeepforest',
      'Captain Cuddles',
      'Jr Jam',
      'Blub',
      'Queen Boo',
      'Yqua',
      'GhostlyCat',
      'Sch',
      'Talion',
      'ABIDE',
      'Jcool',
      'Soap',
      'Sosa',
      'Slipdash',
      'Zach',
      'Kotaru',
      'LP3Cinema',
      'ChunkyPotato',
      'Frankietron',
      'Justice Network',
      'n8',
      'Porygon24',
      'Randall',
      'Sinister',
      'Tim',
      'SoMuchWessel',
      'Xylyntial',
      'Caucxican',
      'Anty',
      'Bot3',
      'SoggyDoggy',
      'Autumn',
      'Crouton',
      'Jets',
      'megataco101',
      'Michael Collins',
      'Monkey',
      'snwflayke',
      'SeanPawn',
      'Setsky',
      'Jeviled Cakeman',
      'Outdatedmemes',
      '8322',
      'AZJ',
      'ITzSweed',
      'Mudvakipper',
      'P8R8 C8D88N8',
      'Ryumaru',
      'SuperNewb',
      'turtleneckthomas',
      'Volt790',
      'Eeveon',
      'Steven',
      'Tankster09',
      'Pablo',
      'boosie_manman',
      'Airswimmer',
      'Archy',
      'Constructor',
      'Shaum',
      'Xanderoni',
      'Drew P',
      'Fraise',
      'PotatoOnCrack',
      'fiend',
      'LordTRex',
      'Toyful',
      'Mr. Rab',
      'IndigoSteel',
      'Aros',
      'BowsertheLord',
      'Cybit',
      'fite me',
      'jakeatkinsonlmao',
      'lvl5accelerator',
      'Rocky28447',
      'S1lentEye',
      'ShiftyVixen',
      'Brave Bi-tender Jill',
      'monoTHEPLEB',
      'Dan',
      'Main',
      'DJ Felix',
      'SpoonerGG',
      'Lasse',
      'Captain Groin',
      'Elliot',
      'Toad',
      'Shadoroth',
      'ImTheFact',
      'Thomlin',
      'Privatepikachu',
      'BasedZin',
      'xo',
      'googuy56',
      'Atsuji-chan',
      'Devotion',
      'Diogo_Stocker_',
      'magi',
      'Neoleouf',
      'Precision',
      'puff69',
      'Qam',
      'Qwerty',
      'TenaciousS P',
      'Zalkyria',
      'zombiejesus',
      'Teriot',
      'Ant',
      'Just Jam',
      'Legion',
      'Hatn\'Hoodie',
      'Inboundz',
      'BX',
      'it\'s Sam!',
      'xmat123x',
      'Astral',
      'benthenerd',
      'Aavel',
      'Axem',
      'Doubledeuce',
      'gg9brother',
      'Huey',
      'Jigglybuff',
      'MegaJazz',
      'Redwood',
      'slaylah',
      'Souzooka',
      'Swiz',
      'Toast',
      'Akira',
      'BillmurianShades',
      'StylinNProfilin',
      'Dark Boo',
      'Logic',
      'My kiD',
      'Rid',
      'ThatLuigi',
      'Frijolito Azul',
      'Smugmeister',
      'Telepwnt',
      'Alec Plays',
      'Kamoshida',
      'SmilinglnMonotone',
      'HeroLightz',
      'Arctic Wolf',
      'Bimnir',
      'Bluefire',
      'Bluej',
      'Braedic',
      'Cameron',
      'CarlosFlare',
      'ChillBoi',
      'Chronic Sleeper',
      'Clomb',
      'Donnie',
      'DreamingHero',
      'EB Games',
      'ez',
      'GoForSpwook',
      'Hale',
      'Hologram',
      'Juiceman',
      'King Jebus',
      'Kryticate',
      'Loganizareject',
      'MassivxCrafter',
      'Mati Claus',
      'Michael',
      'MLK',
      'NoxDecious',
      'RepellantEarth',
      'Skypi',
      'Sunglasses',
      'TheBKain',
      'Triforce141',
      'WitherMan',
      'Aringon',
      'Bubis5murf1nDekU',
      'drewby',
      'Edgy teen that does memes',
      'gsjan',
      'Hata',
      'KakarotCake',
      'Quicksave',
      'Raptor',
      'Roman Royalty',
      'tamatamago',
      'Tubular Bells',
      'ultimate detective',
      'Leafo',
      'ABSOFRUITALICIOUS',
      'Diet Christian',
      'l3engee',
      'lemme_smash_bro',
      'Lidrume',
      'MonoDJ',
      'MysteriousAeon',
      'nathan1394',
      'Nictendo',
      'Pineappleforfun',
      'Rezei',
      'RuMuN',
      'ScarFaze',
      'Slickk',
      'Only played the newest one',
      'Stxrz',
      'nikki',
      'AleksHD',
      'シグ',
      'Slug',
      'Seagate Fanboy',
      'PicklePlays',
      'AshenAF92',
      'jth',
      'Magik',
      'MajorSinclair',
      'AdamGamer4345',
      'B-Rabbit',
      'Big Boss Oscor',
      'CITX406',
      'Cute E',
      'Data',
      'Destro506',
      'dope a memes',
      'DoubleC',
      'Dukazz',
      'Gaxa',
      'Ghost',
      'iRelease',
      'Izlann',
      'Jigglypuff',
      'John',
      'Kazoo +',
      'Killroy',
      'KindredWings',
      'lil tobi',
      'Lissom +',
      'Luna',
      'merk',
      'mjchickenwar',
      'mondelointain',
      'PartlyAwesome',
      'qhawa',
      'Raven',
      'RC Samster',
      'Rob',
      'ryitpls',
      'Shutterstock',
      'Soupy',
      'StormHai',
      'Suhloth',
      'Tortixe',
      'Us er',
      'Walpla',
      'WyFyAaron',
      'YazuThePotato',
      'Zetsubou',
      'Bananation',
      'DevilishJho',
      'Dom926',
      'MuffinJets',
      'Neo-Rewrite',
      'Paris',
      'Rider',
      'Skriller',
      'snowyh',
      'Tarantino',
      'thatguy',
      'H4Z4RD',
      'Angel64Nes',
      'Apple',
      'Ben',
      'Berry',
      'Chocer24',
      'Ciggy',
      'DarkFERDY',
      'Dashonyourboy',
      'Donald_Trump46',
      'FuriousTH',
      'Jef',
      'Lauria',
      'Marin',
      'Mercenarytank15',
      'Mr.Monkey',
      'Penguin',
      'Russian',
      'SidGarcia',
      'Stoven',
      'Thunder Thot',
      'Xea',
      'Zero Imposter',
      'Charitas',
      'FatAss',
      'Fluddulation',
      'Kamt',
      'Mr. Dreamcast',
      'PACEY',
      'ApuKaragoz1',
      'nogoodusername',
      'capitalists',
      'IUndercoverTroll',
      'GEV',
      'Drizz',
      'marti stari',
      'Amusement 64',
      'BeardyBoi',
      'Bhola',
      'carlongos2',
      'Clemo7',
      'dante',
      'Darkfuree',
      'DonkeyKong',
      'Fisto',
      'Freedom',
      'Ghost the superstar',
      'Giga_Byte',
      'GreenTea',
      'Haileystraza',
      'HydraToad',
      'jig',
      'jwtweeds',
      'Kernal',
      'Kev\'s Sis',
      'Korean',
      'Lilli',
      'LoserWithNoLife',
      'Marios',
      'NWwind',
      'OneRockyBoi',
      'PlasmicNeon',
      'Porcupine',
      'Rex',
      'Ricky',
      'RVOtakuMike',
      'Saxton',
      'ScufMePappi',
      'silentreverb',
      'simsora13',
      'Splatooned',
      'Surelook',
      'switchking2001',
      'ThatOtherNarwhalKid',
      'TheDarkDuck',
      'trisha',
      'unique',
      'WilliamWhite',
      'witch',
      'Wow',
      'Zekko',
      'Zhizn',
      'Zilvinas2',
      'Zor-oh',
      '2 girls 1 quick',
      'alexxx',
      'Blackjack',
      'Blinshers',
      'Brisk',
      'Danielio',
      'Debby democrats',
      'Fivavoa',
      'Luigidude',
      'Matheus Staffa',
      'Mayonetta',
      'mew182',
      'QueenNatalie',
      'RedNeo',
      'Ritz',
      'SinsOfMercury',
      'thetkmaster',
      'tylerfunf555',
      'Antasmita',
      'BeeKane',
      'Bogan',
      'bonez1127',
      'Chazo',
      'cubeslice',
      'Curator',
      'Flint',
      'FreestyleVertex',
      'fwooshy',
      'HotHeart123',
      'HREball',
      'Jabuns',
      'Jessie',
      'Joycon',
      'Kebabman13',
      'KrayzieBone',
      'La Manta Rata',
      'peace.guacamole',
      'Pistachio',
      'prommac',
      'Samurai Jack',
      'squid',
      'The Gamer Boy',
      'Urban Duck',
      'Willeyd',
      'bludud101',
      'Katsuki',
      'TheFugliestToad',
      'Arab',
      'CrusadeKun',
      'Dragon Emperor',
      'Magolor',
      'AC',
      'Tower',
      'Doregami',
      'Regular Krooze',
      'airon1423',
      'Atlas',
      'ZoomZike',
      'Bootysnorkel',
      'Stardust Mirage',
      'Gabe Elric',
      'kkirby999',
      'Cole',
      'Meeky',
      'steve_o9219',
      'Quiggs',
      'MandL27',
      'Pickle Cat',
      'Pretelethal',
      'Rojo',
      'Naythen',
      'Kazuya',
      'Platy',
      'Noah Layta',
      'bunny',
      'megaboyX97',
      'Slide56Attack',
      'Jala',
      'lostinthesauce',
      'Slick',
      'SSGSS Knight',
      'TroyDeeneybigman',
      'BaraPanda',
      'SupremeNachoe',
      'c-lu',
      'David',
      'Guyute',
      'Airion',
      'Scannerwary',
      'Black Diamond',
      'Ninja PLZ 216',
      'Sgt Suicide',
      '9877Gamer',
      'Yanqui',
      'Mtnmike19',
      'vroom',
      'Ger',
      'Elyx',
      'NinjaShaker724',
      'Chep',
      'Fleur',
      'fieiodkdledlddkk',
      'Roost',
      'Tom Lincoln',
      'Kengar Dongatron',
      'MikaLaShay',
      'SuperSquid004',
      'J A Y .exe',
      'Daniel',
      'Shaolin Turtle',
      'Paradise',
      'wario716',
      'Justin (J-Bone)',
      'Gifty',
      'Player 2',
      'Moras Zon',
      'TheBlackPacman',
      'evilqueen',
      'psudodudo',
      'Kira',
      'avocalex',
      'mina',
      'Jug',
      'Shigu',
      'Sneaky Shadow',
      'realkitty56',
      'it\'s Mario',
      'l_00G1',
      'C. Pariah',
      'SirJimbo070',
      'Kyle',
      'Dark Ninja',
      'Ethan0622',
      'Beetloafs',
      'Starry',
      'xClayx',
      'Mr2Seconds',
      'sloppy',
      'Spergius06',
      'Post',
      'Ravin',
      'Gluttony',
      'KipSizes',
      'ayden',
      'Zipette',
      'Jaylean',
      'JoesephDLS',
      'BeatDaMeat',
      'balibrera',
      'Acestar',
      'PlasmaWhirl',
      'HyDread',
      'Hex',
      'kingboo056',
      'SoboKing',
      'samrun1',
      'DisneyFilipino',
      'cumin',
      'J.R~',
      'Rolf2heBolf',
      'MJofMarioParty',
      'MeryDd91',
      'mautown',
      'Remi',
      'BreadBilly',
      'JessMess64',
      'crutch king 88',
      'Yoshi Negro',
      'Edge',
      'ocianbb',
      'TeebTimboe',
      'iftupacwasback',
      'Marmogolf',
      'Triyur',
      'Oath Flame Tendou of Time',
      'RiceKrispy',
      'Dr. Overzealous',
      'Yukes',
      'Narrcidaisy',
      'Exo',
      'CherryX2',
      'hatman64',
      'barrelbreak',
      'The_Col',
      'ProjectSeeks',
      'froot',
      'Kadesh',
      'The Tubby Sandshrew Files',
      'Cellabelle729',
      'AlbinoRhino',
      'Fury13',
      'ElykTsorb',
      'LexiXander',
      'Admiralfunk',
      'yop',
      'tokig',
      'Lupino',
      'Heartless',
      'GIGAMATIC',
      'theGSeagle',
      'humaneshadow',
      'roscoxc',
      'Knightmare',
      'Blaze',
      'Byleth Simp',
      'kirmato',
      'Geomint',
      'HappyMajoraMask',
      'GamerLetter',
      'bella',
      'Jonononononathan',
      'INKevin',
      'Maro',
      'Rantaray',
      'Sonickirby',
      'xBlankPagex',
      'paynerus',
      'Calvin Steelbeetle',
      'Frisbee',
      'AFKLink',
      'spongemattb',
      'HellJumper',
      'Kabane Kusaka',
      'Bones',
      'Saltyrice',
      'AbeLit',
      'Chris ThreeLeaf',
      'groxhead',
      'PrabsterLobster',
      'kornelbut',
      'Ethan.',
      'walrus446',
      'Jillybean',
      'tordread',
      'Swiftie',
      'RPhil',
      'Augu',
      'Cezar Andrade',
      'MarioMadness130',
      'Uranus',
      'Imfernol',
      'ChaosDiscord',
      'SKY',
      'Scottman60',
      'DrBlueFace',
      'scowen',
      'Nick123_leafshield',
      'mitodospro',
      'Chase Your Goals',
      'Zlegend',
      'kvylv_Ivsh',
      'light738',
      'properpronoun',
      'Gilberto',
      'Froakie',
      'Quality Content',
      'JustAGrump',
      'MasterGamer95',
      'thedankengine39',
      'NpMaster',
      'LDeathwish',
      'katiiiekat',
      'SharksBo23',
      'Ken6969',
      'alui',
      'redninjapuffle',
      'Spring',
      'superleoncloud',
      'gamefreak105',
      'Giomar',
      'ShadowGirl7',
      'Dylbert',
      'GunSmokeYxX',
      'Paperkirbs',
      'Azure',
      'Pooters',
      'novanima',
      'Doux',
      'gnorgle',
      'Jescobedo',
      'Johbo81',
      'FBE',
      'BuddySmileyFace',
      'Damjal'
]

    SITES = [
      'Mario Party Netplay',
      'Mario Party Legacy',
      'Nintendo.com',
      'Hudson Soft',
      'Party Planner 64',
      'NDCube',
      '4Chan',
      'Miiverse',
      'Nintendo Network'
    ]

    THINGS = [
      "Mario\'s Rainbow Castle",
      "Luigi\'s Engine Room",
      "Yoshi\'s Tropical Island",
      "DK\'s Jungle Adventure",
      "Peach\'s Birthday Cake",
      "Wario\'s Battle Canyon",
      "Bowser\'s Magma Mountain",
      'Eternal Star',
      'Pirate Land',
      'Space Land',
      'Western Land',
      'Horror Land',
      'Bowser Land',
      'Mystery Land',
      'Chilly Waters',
      'Deep Bloober Sea',
      'Spiny Desert',
      'Woody Woods',
      'Creepy Cavern',
      "Waluigi\'s Island",
      "Toad\'s Midway Mania",
      "Goomba\'s Greedy Gala",
      "Shy Guy\'s Jungle Jam",
      "Boo\'s Haunted Bash",
      "Koopa\'s Seaside Soiree",
      "Bowser\'s Gnarly Party",
      'Toy Dream',
      'Pirate Dream',
      'Undersea Dream',
      'Future Dream',
      'Sweet Dream',
      'Rainbow Dream',
      "Bowser\'s Nightmare",
      'Faire Square',
      'Towering Treetop',
      "E Gadd\'s Garage",
      "Snowflake Lake",
      'Castaway Bay',
      'Clockwork Castle',
      'Grand Canal',
      'Pagoda Peak',
      'Pyramid Park',
      'Neon Heights',
      'Windmillville',
      "Bowser\'s Enchanted Inferno",
      "DK\'s Treetop Temple",
      "Goomba\'s Booty Boardwalk'",
      "King Boo\'s Haunted Hideaway",
      "Shy Guy\'s Perplex Express",
      "Koopa\'s Tycoon Town",
      "Bowser\'s Warped Orbit"
    ]

    PACKS = [
      'Mario Party 1',
      'Mario Party 2',
      'Mario Party 3',
      'Mario Party 4',
      'Mario Party 5',
      'Mario Party 6',
      'Mario Party 7',
      'Mario Party 8',
      'Mario Party 9',
      'Mario Party 10',
      'Mario Party DS',
      'Mario Party: Island Tour',
      'Mario Party: Star Rush',
      'Mario Party: The Top 100',
      'Mario Party Advance',
      'Mario Party Superstars',
      'Mario Party e',
      'Super Mario Party',
    ]

    FUNCTIONS = [
      'Blue Space',
      'Red Space',
      'Happening Space',
      'Star Space',
      'Orb Space',
      'Item Space',
      'Game Guy Space',
      'Duel Space',
      'Battle Space',
      'Lucky Space',
      'Chance Time Space'
    ]

    DRAMA = [
      'bugs',
      'crashes',
      'drama',
      'lots of drama',
      'imbalance',
      'pain and suffering',
      'piracy'
    ]

    ADJECTIVES = [
      'bad',
      'wrong',
      'illegal',
      'horrible',
      'nasty',
      'not in MPN',
      'noncompliant with Mojang\'s EULA',
      'a serious problem',
      'incompatible',
      'a waste of time',
      'wonderful',
      'amazing',
      'toxic',
      'shameful',
      'disappointing',
      'bloated',
      'outdated',
      'incorrect',
      'full of drama',
      'too realistic'
    ]

    BADSOFT = [
      'malware',
      'spyware',
      'adware',
      'DRM',
      'viruses',
      'trojans',
      'keyloggers',
      'stolen code',
      'easter eggs',
      'potential login stealers',
      'adf.ly links',
      'bad code',
      'stolen assets',
      'malicious code',
      'secret backdoors'
    ]

    CRASHES = [
      'crash',
      'explode',
      'break',
      'lag',
      'blow up',
      'corrupt game'
    ]

    BANS = [
      'call bowser'
      'move the star'
      'cover an orb space'
      'steal a star',
      'shame',
      'destroy',
      'activate chance time'
    ]

    CODE = [
      'code',
      'assets',
      'ideas',
      'concepts',
      'a single function',
      '5 lines of code',
      'a class',
      'a few files',
      'a ZIP file',
      'a ASM file',
      'a C file',
      'a JSON board'
      'a GitHub repository'
    ]

    ADVERBS = [
      'worse',
      'better',
      'faster',
      'slower',
      'more stable',
      'less buggy',
      'less stable',
      'more buggy'
    ]

    BADVERBS = [
      'steals coins',
      'destroy the life of',
      'steals a star',
      'steals multiple stars',
      'cause drama about',
      'complain about',
      'kick',
      'z-star',
      'steal from',
      'use Boo against',
    ]

    PRICES = [
      '$200',
      '$250',
      '$300',
      '$350',
      '$400',
      '$450',
      '$500',
      '$600'
    ]

    ACTIVATES = [
      'activates',
      'works',
      'functions',
      'breaks'
    ]

    SAYS = [
      'says',
      'tweets',
      'claims',
      'confirms',
      'denies'
    ]

    SIZES = [
      'little',
      'tiny',
      'big',
      'large',
      'huge',
      'gigantic',
      'enormous'
    ]

    SENTENCES = [
      '%{people} launched a DoS attack on the website of %{things}',
      '%{sites} urges everyone to stop using %{things}',
      'After a %{enormous} amount of requests, %{packs} removes %{things}',
      'After a %{enormous} amount of requests, %{packs} adds %{things}',
      'After a %{enormous} amount of requests, %{packs} adds %{function} to %{things}',
      '%{people} plays %{things} on Twitch',
      '%{people} fixes %{function} in %{things} to be unlike %{things}',
      '%{things} makes %{things} %{crash}, %{sites} users complain',
      '%{people} complained about being in %{things} on %{sites}',
      '%{people} releases %{code} of %{things} for %{price}',
      '%{sites} considers %{things} worse than %{things}',
      '%{people} made %{things} depend on %{things}',
      '%{people} bans %{people} from using %{things} in %{packs}',
      '%{people} complains that %{things} discussion doesn\'t belong on %{sites}',
      '%{people} has a Patreon goal to add %{function} to %{things} for %{price} a month',
      '%{people} has a Patreon goal to add %{things} compatibility to %{things} for %{price} a month',
      '%{people} complains that %{people} replaced %{things} by %{things}',
      '%{people} complains that %{people} replaced %{things} by %{things} in %{packs}',
      '%{people} complains that %{people} removed %{function} in %{packs}',
      '%{people} decided that %{things} is too %{adj} and replaced it with %{things}',
      '%{people} %{says} %{things} is %{adj}.',
      '%{people} %{says} %{things} is literally %{adj}.',
      '%{things} is not updated for the latest version of Minecraft.',
      '%{people} removes %{things} from %{packs}.',
      '%{people} adds %{things} to %{packs}.',
      '%{people} quits modding. Fans of %{things} rage.',
      '%{people} is found to secretly like %{things}',
      '%{people} openly hates %{function} in %{things}',
      '%{people} threatens to %{ac1} %{people} until they remove %{things} from %{packs}',
      '%{people} threatens to %{ac1} %{people} until they remove %{function} from %{things}',
      '%{people} threatens to %{ac1} %{people} until they add %{function} to %{things}',
      '%{people} came out in support of %{things}',
      '%{people} came out in support of %{drama}',
      '%{people} and %{people} came out in support of %{drama}',
      '%{people} came out against %{drama}, %{sites} rages',
      '%{people} and %{people} came out against %{drama}, %{sites} rages',
      '%{people} forks %{things} causing %{drama}',
      '%{people} %{says} to replace %{things} with %{things}',
      '%{people} %{says} %{people} causes drama',
      '%{things} fans claim that %{things} should be more like %{things}',
      '%{things} fans claim that %{things} should have better %{function}',
      '%{people} %{says} that %{things} should be more like %{things}',
      '%{people} %{says} that %{things} should be less like %{things}',
      '%{people} rebalances %{things} for %{packs}',
      '%{people} adds %{function} to %{things} by request of %{people}',
      '%{people} removes %{function} from %{things} by request of %{people}',
      '%{people} removes compatibility between %{things} and %{things} by request of %{people}',
      '%{people} %{says} %{people}\'s attitude is %{adj}',
      '%{people} %{says} %{sites}\'s attitude is %{adj}',
      '%{people} quits the development team of %{things}',
      '%{people} %{says} %{things} is too much like %{things}',
      '%{people} %{says} %{things} is a ripoff of %{things}',
      '%{people} %{says} %{people} stole %{code} from %{people}',
      '%{people} %{says} %{people} did not steal %{code} from %{people}',
      '%{people} decides to %{ban} %{people} from %{packs}',
      '%{things} doesn\'t work with %{things} since the latest update',
      '%{people} sues %{things}',
      '%{people} %{says} %{things} is %{adj} on %{sites}',
      '%{people} %{says} %{things} is full of %{badsoft}',
      '%{people} %{says} %{things} causes %{drama}',
      '%{people} %{says} %{things} causes %{drama} when used with %{things}',
      '%{people} %{says} using %{things} and %{things} together is %{adj}',
      '%{people} rants about %{things} on %{sites}',
      '%{people} rants about %{function} in mods on %{sites}',
      '%{people} steals code from %{things}',
      '%{things} breaks %{function}',
      '%{people} sues %{things} developers',
      '%{people} reminds you that %{things} is %{adj}',
      '%{people} and %{people} get into a drama fight on %{sites}',
      'Fans of %{things} and %{things} argue on %{sites}',
      '%{people} and %{people} argue about %{things}',
      '%{people} puts %{badsoft} in %{things}',
      '%{people} complains about %{things} breaking %{things}',
      '%{people} complains about %{things} breaking %{function}',
      '%{people} complains about %{things} including %{function}',
      '%{things} breaks %{function} in %{things}',
      '%{things} breaks %{things} support in %{things}',
      '%{things} adds code to %{ban} %{people} automatically',
      '%{things} adds code to %{ban} people using %{things}',
      '%{things} removes compatibility with %{things}',
      '%{people} %{says} not to use %{things}',
      '%{people} %{says} not to use %{things} with %{things}',
      '%{people} finds %{badsoft} in %{things}',
      '%{people} drew a nasty graffiti about %{people}',
      '%{people} drew a nasty graffiti about %{things}',
      '%{things} makes %{things} %{crash} when used with %{things}',
      '%{things} makes %{things} %{crash} when used by %{people}',
      '%{things} makes %{things} crash %{things} when used by %{people}',
      '%{things} adds %{badsoft} that only %{activates} in %{packs}',
      '%{things} adds %{badsoft} that only %{activates} alongside %{things}',
      '%{things} makes %{people} invincible from %{things} in %{packs}',
      '%{people} decides to base their entire modpack on %{things}',
      '%{people} tweaks balance in %{things} too much, annoying %{sites}',
      '%{people} tweaks balance in %{things} too much, annoying %{people}',
      '%{people} %{says} %{people} is %{worse} than %{people}',
      '%{people} %{says} %{things} is %{worse} than %{things}',
      '%{people} bans %{people} from %{sites}'
    ]
  end
end
